CREATE TABLE [dbo].[AspNetUsers] (
    [Id]                      NVARCHAR (450)     NOT NULL,
    [AccessFailedCount]       INT                NOT NULL,
    [ConcurrencyStamp]        NVARCHAR (MAX)     NULL,
    [Email]                   NVARCHAR (256)     NULL,
    [EmailConfirmed]          BIT                NOT NULL,
    [LockoutEnabled]          BIT                NOT NULL,
    [LockoutEnd]              DATETIMEOFFSET (7) NULL,
    [NormalizedEmail]         NVARCHAR (256)     NULL,
    [NormalizedUserName]      NVARCHAR (256)     NULL,
    [PasswordHash]            NVARCHAR (MAX)     NULL,
    [PhoneNumber]             NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed]    BIT                NOT NULL,
    [SecurityStamp]           NVARCHAR (MAX)     NULL,
    [TwoFactorEnabled]        BIT                NOT NULL,
    [UserName]                NVARCHAR (256)     NULL,
    [FirstName]               NVARCHAR (100)     NULL,
    [LastName]                NVARCHAR (100)     NULL,
    [CountryId]               INT                NULL,
    [DepartmentId]            INT                NULL,
    [FullName]                NVARCHAR (201)     NULL,
    [LocationId]              INT                NULL,
    [StaffLevelId]            INT                NULL,
    [BackupApprover]          NVARCHAR (MAX)     NULL,
    [DefaultApprover]         NVARCHAR (MAX)     NULL,
    [EmployeeNumber]          NVARCHAR (MAX)     NULL,
    [Active]                  BIT                NOT NULL,
    [SapId]                   INT                NULL,
    [ExpectedDepartureDate]   DATETIME2 (7)      NULL,
    [JobTitle]                NVARCHAR (MAX)     NULL,
    [Notes]                   NVARCHAR (MAX)     NULL,
    [PromotionRole]           NVARCHAR (MAX)     NULL,
    [StartDate]               DATETIME2 (7)      NULL,
    [ManagerId]               NVARCHAR (450)     NULL,
    [HiringManagerId]         NVARCHAR (450)     NULL,
    [JobGradeId]              NVARCHAR (450)     NULL,
    [Address1]                NVARCHAR (MAX)     NULL,
    [Address2]                NVARCHAR (MAX)     NULL,
    [Age]                     INT                NULL,
    [BambooHrDepartment]      NVARCHAR (MAX)     NULL,
    [BambooHrJobCat]          NVARCHAR (MAX)     NULL,
    [BambooHrLocation]        NVARCHAR (MAX)     NULL,
    [DateOfBirth]             NVARCHAR (MAX)     NULL,
    [EmploymentHistoryStatus] NVARCHAR (MAX)     NULL,
    [Ethnicity]               NVARCHAR (MAX)     NULL,
    [Gender]                  NVARCHAR (MAX)     NULL,
    [HomeCity]                NVARCHAR (MAX)     NULL,
    [HomeCountry]             NVARCHAR (MAX)     NULL,
    [HomeEmail]               NVARCHAR (MAX)     NULL,
    [HomePhone]               NVARCHAR (MAX)     NULL,
    [HomeState]               NVARCHAR (MAX)     NULL,
    [HomeZipCode]             NVARCHAR (MAX)     NULL,
    [MaritalStatus]           NVARCHAR (MAX)     NULL,
    [MiddleName]              NVARCHAR (MAX)     NULL,
    [MobilePhone]             NVARCHAR (MAX)     NULL,
    [SupervisorEid]           NVARCHAR (MAX)     NULL,
    [SupervisorId]            NVARCHAR (MAX)     NULL,
    [TerminationDate]         NVARCHAR (MAX)     NULL,
    [WorkPhone]               NVARCHAR (MAX)     NULL,
    [HireDate]                NVARCHAR (MAX)     NULL
);

