CREATE TABLE [dbo].[BambooHrEmployees] (
    [BambooHrID]              INT            NULL,
    [EmployeeNumber]          INT            NULL,
    [LastChanged]             DATETIME2 (7)  NULL,
    [Status]                  NVARCHAR (20)  NULL,
    [FullName]                NVARCHAR (200) NULL,
    [FirstName]               NVARCHAR (100) NULL,
    [MiddleName]              NVARCHAR (100) NULL,
    [LastName]                NVARCHAR (100) NULL,
    [Gender]                  NVARCHAR (10)  NULL,
    [DateOfbirth]             DATETIME       NULL,
    [HireDate]                DATETIME       NULL,
    [Age]                     INT            NULL,
    [Address1]                NVARCHAR (100) NULL,
    [Address2]                NVARCHAR (100) NULL,
    [City]                    NVARCHAR (30)  NULL,
    [State]                   NVARCHAR (20)  NULL,
    [Country]                 NVARCHAR (20)  NULL,
    [ZipCode]                 NVARCHAR (20)  NULL,
    [HomeEmail]               NVARCHAR (100) NULL,
    [HomePhone]               NVARCHAR (15)  NULL,
    [MobilePhone]             NVARCHAR (15)  NULL,
    [Email]                   NVARCHAR (100) NULL,
    [WorkPhone]               NVARCHAR (15)  NULL,
    [JobTitle]                NVARCHAR (100) NULL,
    [Department]              NVARCHAR (100) NULL,
    [Location]                NVARCHAR (100) NULL,
    [JobCategory]             NVARCHAR (100) NULL,
    [TerminationDate]         DATETIME       NULL,
    [SupervisorID]            INT            NULL,
    [SupervisorEID]           INT            NULL,
    [EmploymentHistoryStatus] NVARCHAR (20)  NULL,
    [MaritalStatus]           NVARCHAR (20)  NULL,
    [Nationality]             NVARCHAR (50)  NULL
);

