CREATE TABLE [dbo].[VIP_Employee] (
    [CompanyNumber]       SMALLINT        NOT NULL,
    [EmployeeCode]        VARCHAR (8)     NOT NULL,
    [DateEngaged]         DATE            NULL,
    [Surname]             VARCHAR (24)    NULL,
    [FullNames]           VARCHAR (35)    NULL,
    [IDNumber]            VARCHAR (16)    NULL,
    [DateOfBirth]         DATE            NULL,
    [Gender]              VARCHAR (1)     NULL,
    [MaritalStatus]       VARCHAR (1)     NULL,
    [EmployeeStatus]      VARCHAR (1)     NULL,
    [TerminationDate]     DATE            NULL,
    [CellPhoneNo]         VARCHAR (20)    NULL,
    [EMailAddress]        VARCHAR (60)    NULL,
    [BankAccountType]     VARCHAR (1)     NULL,
    [BankClearanceNo]     INT             NULL,
    [BankName]            VARCHAR (50)    NULL,
    [BranchName]          VARCHAR (50)    NULL,
    [BankAccountNumber]   VARCHAR (50)    NULL,
    [AccountHolderName]   VARCHAR (30)    NULL,
    [JobGradeCode]        VARCHAR (8)     NULL,
    [PaypointCode]        VARCHAR (4)     NULL,
    [JobTitleLongDesc]    VARCHAR (35)    NULL,
    [CategoryCode]        VARCHAR (30)    NULL,
    [DepartmentCode]      VARCHAR (4)     NULL,
    [GLAccountGroup]      VARCHAR (6)     NULL,
    [Earnings_01]         NUMERIC (11, 2) NULL,
    [Earnings_02]         NUMERIC (11, 2) NULL,
    [Earnings_03]         NUMERIC (11, 2) NULL,
    [Earnings_04]         NUMERIC (11, 2) NULL,
    [Earnings_05]         NUMERIC (11, 2) NULL,
    [Earnings_06]         NUMERIC (11, 2) NULL,
    [Earnings_07]         NUMERIC (11, 2) NULL,
    [Earnings_08]         NUMERIC (11, 2) NULL,
    [Earnings_09]         NUMERIC (11, 2) NULL,
    [Earnings_10]         NUMERIC (11, 2) NULL,
    [Earnings_11]         NUMERIC (11, 2) NULL,
    [Earnings_12]         NUMERIC (11, 2) NULL,
    [Earnings_13]         NUMERIC (11, 2) NULL,
    [Earnings_14]         NUMERIC (11, 2) NULL,
    [Earnings_15]         NUMERIC (11, 2) NULL,
    [Earnings_16]         NUMERIC (11, 2) NULL,
    [Earnings_17]         NUMERIC (11, 2) NULL,
    [Earnings_18]         NUMERIC (11, 2) NULL,
    [Earnings_19]         NUMERIC (11, 2) NULL,
    [Earnings_20]         NUMERIC (11, 2) NULL,
    [Earnings_21]         NUMERIC (11, 2) NULL,
    [Earnings_22]         NUMERIC (11, 2) NULL,
    [Earnings_23]         NUMERIC (11, 2) NULL,
    [Earnings_24]         NUMERIC (11, 2) NULL,
    [Earnings_25]         NUMERIC (11, 2) NULL,
    [Earnings_26]         NUMERIC (11, 2) NULL,
    [Earnings_27]         NUMERIC (11, 2) NULL,
    [Earnings_28]         NUMERIC (11, 2) NULL,
    [Earnings_29]         NUMERIC (11, 2) NULL,
    [Earnings_30]         NUMERIC (11, 2) NULL,
    [Earnings_31]         NUMERIC (11, 2) NULL,
    [Earnings_32]         NUMERIC (11, 2) NULL,
    [Earnings_33]         NUMERIC (11, 2) NULL,
    [Earnings_34]         NUMERIC (11, 2) NULL,
    [Earnings_35]         NUMERIC (11, 2) NULL,
    [Earnings_36]         NUMERIC (11, 2) NULL,
    [Earnings_37]         NUMERIC (11, 2) NULL,
    [Earnings_38]         NUMERIC (11, 2) NULL,
    [Earnings_39]         NUMERIC (11, 2) NULL,
    [Earnings_40]         NUMERIC (11, 2) NULL,
    [Earnings_41]         NUMERIC (11, 2) NULL,
    [Earnings_42]         NUMERIC (11, 2) NULL,
    [Earnings_43]         NUMERIC (11, 2) NULL,
    [Earnings_44]         NUMERIC (11, 2) NULL,
    [Earnings_45]         NUMERIC (11, 2) NULL,
    [Ded_01]              NUMERIC (11, 2) NULL,
    [Ded_02]              NUMERIC (11, 2) NULL,
    [Ded_03]              NUMERIC (11, 2) NULL,
    [Ded_04]              NUMERIC (11, 2) NULL,
    [Ded_05]              NUMERIC (11, 2) NULL,
    [Ded_06]              NUMERIC (11, 2) NULL,
    [Ded_07]              NUMERIC (11, 2) NULL,
    [Ded_08]              NUMERIC (11, 2) NULL,
    [Ded_09]              NUMERIC (11, 2) NULL,
    [Ded_10]              NUMERIC (11, 2) NULL,
    [Ded_11]              NUMERIC (11, 2) NULL,
    [Ded_12]              NUMERIC (11, 2) NULL,
    [Ded_13]              NUMERIC (11, 2) NULL,
    [Ded_14]              NUMERIC (11, 2) NULL,
    [Ded_15]              NUMERIC (11, 2) NULL,
    [Ded_16]              NUMERIC (11, 2) NULL,
    [Ded_17]              NUMERIC (11, 2) NULL,
    [Ded_18]              NUMERIC (11, 2) NULL,
    [Ded_19]              NUMERIC (11, 2) NULL,
    [Ded_20]              NUMERIC (11, 2) NULL,
    [Ded_21]              NUMERIC (11, 2) NULL,
    [Ded_22]              NUMERIC (11, 2) NULL,
    [Ded_23]              NUMERIC (11, 2) NULL,
    [Ded_24]              NUMERIC (11, 2) NULL,
    [Ded_25]              NUMERIC (11, 2) NULL,
    [Ded_26]              NUMERIC (11, 2) NULL,
    [Ded_27]              NUMERIC (11, 2) NULL,
    [Ded_28]              NUMERIC (11, 2) NULL,
    [Ded_29]              NUMERIC (11, 2) NULL,
    [Ded_30]              NUMERIC (11, 2) NULL,
    [Ded_31]              NUMERIC (11, 2) NULL,
    [Ded_32]              NUMERIC (11, 2) NULL,
    [Ded_33]              NUMERIC (11, 2) NULL,
    [Ded_34]              NUMERIC (11, 2) NULL,
    [Ded_35]              NUMERIC (11, 2) NULL,
    [Ded_36]              NUMERIC (11, 2) NULL,
    [Ded_37]              NUMERIC (11, 2) NULL,
    [Ded_38]              NUMERIC (11, 2) NULL,
    [Ded_39]              NUMERIC (11, 2) NULL,
    [Ded_40]              NUMERIC (11, 2) NULL,
    [Ded_41]              NUMERIC (11, 2) NULL,
    [Ded_42]              NUMERIC (11, 2) NULL,
    [Ded_43]              NUMERIC (11, 2) NULL,
    [Ded_44]              NUMERIC (11, 2) NULL,
    [Ded_45]              NUMERIC (11, 2) NULL,
    [CompContribFixed_01] NUMERIC (11, 2) NULL,
    [CompContribFixed_02] NUMERIC (11, 2) NULL,
    [CompContribFixed_03] NUMERIC (11, 2) NULL,
    [CompContribFixed_04] NUMERIC (11, 2) NULL,
    [CompContribFixed_05] NUMERIC (11, 2) NULL,
    [CompContribFixed_06] NUMERIC (11, 2) NULL,
    [CompContribFixed_07] NUMERIC (11, 2) NULL,
    [CompContribFixed_08] NUMERIC (11, 2) NULL,
    [CompContribFixed_09] NUMERIC (11, 2) NULL,
    [CompContribFixed_10] NUMERIC (11, 2) NULL,
    [CompContribFixed_11] NUMERIC (11, 2) NULL,
    [CompContribFixed_12] NUMERIC (11, 2) NULL,
    [CompContribFixed_13] NUMERIC (11, 2) NULL,
    [CompContribFixed_14] NUMERIC (11, 2) NULL,
    [CompContribFixed_15] NUMERIC (11, 2) NULL,
    [CompContribFixed_16] NUMERIC (11, 2) NULL,
    [CompContribFixed_17] NUMERIC (11, 2) NULL,
    [CompContribFixed_18] NUMERIC (11, 2) NULL,
    [CompContribFixed_19] NUMERIC (11, 2) NULL,
    [CompContribFixed_20] NUMERIC (11, 2) NULL,
    [CountryCode]         NVARCHAR (10)   NULL,
    [SwiftCode]           VARCHAR (30)    NULL,
    [MMNumber]            VARCHAR (40)    NULL,
    [MMName]              VARCHAR (40)    NULL,
    [MMCarrier]           VARCHAR (40)    NULL,
    [PayInfo2]            VARCHAR (30)    NULL,
    [WebUser]             VARCHAR (40)    NULL
);

