CREATE TABLE [dbo].[DimEmployee] (
    [UserID]             INT            IDENTITY (1, 1) NOT NULL,
    [SapID]              INT            NULL,
    [VipID]              INT            NULL,
    [BambooHrID]         INT            NULL,
    [FullName]           NVARCHAR (250) NULL,
    [Email]              NVARCHAR (200) NULL,
    [Age]                INT            NULL,
    [Gender]             NVARCHAR (10)  NULL,
    [MaritalStatus]      NVARCHAR (10)  NULL,
    [DepartmentCode]     NVARCHAR (10)  NULL,
    [DepartmentName]     NVARCHAR (50)  NULL,
    [Location]           NVARCHAR (50)  NULL,
    [CategoryCode]       NVARCHAR (50)  NULL,
    [JobTitle]           NVARCHAR (150) NULL,
    [Active]             VARCHAR (3)    NULL,
    [U_WebUser]          NVARCHAR (3)   NULL,
    [VIP]                VARCHAR (3)    NULL,
    [BambooHR]           VARCHAR (3)    NULL,
    [CountryCode]        NVARCHAR (10)  NULL,
    [CountryName]        NVARCHAR (30)  NULL,
    [JobCategory]        NVARCHAR (100) NULL,
    [HomeCountry]        NVARCHAR (13)  NULL,
    [StartDate]          DATETIME2 (0)  NULL,
    [PayGrade]           NVARCHAR (10)  NULL,
    [TerminationDate]    DATETIME       NULL,
    [LocationId]         INT            NULL,
    [DepartmentId]       INT            NULL,
    [CountryId]          INT            NULL,
    [JobGradeId]         NVARCHAR (450) NULL,
    [BambooHrDepartment] NVARCHAR (MAX) NULL,
    [BambooHrLocation]   NVARCHAR (MAX) NULL
);

