CREATE TABLE [dbo].[PromotedEmployees] (
    [BambooHrID]              INT            NULL,
    [FullName]                NVARCHAR (150) NULL,
    [LastName]                NVARCHAR (150) NULL,
    [JobTitle]                VARCHAR (40)   NULL,
    [TerminationDate]         DATETIME       NULL,
    [Nationality]             NVARCHAR (100) NULL,
    [FirstName]               NVARCHAR (100) NULL,
    [MiddleName]              NVARCHAR (100) NULL,
    [BambooHrEmployeeCode]    INT            NULL,
    [Active]                  INT            NULL,
    [StartDate]               DATETIME       NULL,
    [EmailAddress]            VARCHAR (100)  NULL,
    [Source]                  NVARCHAR (8)   NULL,
    [Location]                NVARCHAR (20)  NULL,
    [ApplicationuserID]       NVARCHAR (450) NULL,
    [DepartmentCode]          VARCHAR (50)   NULL,
    [LocationCode]            VARCHAR (50)   NULL,
    [ProjectCode]             NVARCHAR (50)  NULL,
    [JobGradeCode]            VARCHAR (30)   NULL,
    [CityWork]                NVARCHAR (100) NULL,
    [EmploymentHistoryStatus] NVARCHAR (50)  NULL,
    [Source.Source]           NVARCHAR (8)   NULL,
    [DimCountryID]            INT            NULL,
    [BambooHrCountryCode]     NVARCHAR (8)   NULL,
    [DimDepartmentID]         INT            NULL,
    [DimLocationID]           INT            NULL,
    [DimJobGradeID]           INT            NULL,
    [CurrentEmployeeID]       INT            NULL,
    [VIPEmployeeCode]         INT            NULL,
    [VIPCountryCode]          NVARCHAR (10)  NULL
);

