CREATE TABLE [dbo].[SFEmployee] (
    [SFID]              INT              IDENTITY (1, 1) NOT NULL,
    [CountryCode]       NVARCHAR (10)    NULL,
    [DepartmentCode]    VARCHAR (4)      NULL,
    [LocationCode]      VARCHAR (4)      NULL,
    [FullName]          NVARCHAR (350)   NULL,
    [FirstName]         NVARCHAR (150)   NULL,
    [MiddleName]        NVARCHAR (150)   NULL,
    [Active]            INT              NULL,
    [LastName]          NVARCHAR (150)   NULL,
    [JobGradeCode]      VARCHAR (30)     NULL,
    [EmailAddress]      VARCHAR (450)    NULL,
    [EmployeeCode]      INT              NULL,
    [StartDate]         DATETIME         NULL,
    [TerminationDate]   DATETIME         NULL,
    [MMName]            VARCHAR (40)     NULL,
    [MMNumber]          VARCHAR (40)     NULL,
    [MMCarrier]         VARCHAR (40)     NULL,
    [JobTitle]          VARCHAR (100)    NULL,
    [WebUser]           NVARCHAR (10)    NULL,
    [Gender]            NVARCHAR (30)    NULL,
    [MaritalStatus]     NVARCHAR (30)    NULL,
    [Source]            VARCHAR (14)     NULL,
    [PayGrade]          NVARCHAR (30)    NULL,
    [ApplicationUserID] UNIQUEIDENTIFIER NULL,
    [CompanyNumber]     INT              NULL,
    [HRSource]          VARCHAR (8)      NULL,
    [CurrentEmployeeID] INT              NULL,
    [SFUserId]          INT              NULL,
    [LastUpdatedDate]   DATETIME         NULL,
    [BankCode]          VARCHAR (10)     NULL,
    [BankAccountName]   VARCHAR (150)    NULL,
    [BankAccountNumber] VARCHAR (40)     NULL,
    [SwiftCode]         VARCHAR (30)     NULL,
    [RoutingNumber]     VARCHAR (30)     NULL
);

